<a href="https://colab.research.google.com/github/ansh441/BMI_Calculator/blob/main/Merging.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
# create an empty list to store the dataframes
df_list = []
merged_dfMDD = pd.DataFrame()
# loop through each CSV file and append its contents to df_list
for i in range(1,31):
    df = pd.read_csv(f'/content/drive/MyDrive/EC EEGTemporalPreprocessed/DatasetMDD/DatasetMDD{i}.csv')
    df_list.append(df)

# concatenate the dataframes vertically into a single dataframe
# for data in df_list:
#     merged_df = pd.concat(data, axis=0, ignore_index=True)
#     merged_df = pd.concat([df1, d, ignore_index=True)
#     print(merged_df)

merged_dfMDD = pd.concat(df_list, axis=0, ignore_index=True)

# print the merged dataframe
print(merged_dfMDD)

       Fp1_delta  Fp1_theta  Fp1_alpha    Fp1_beta  Fp1_gamma  T7_delta  \
0       6.603542  19.314987  48.768007   41.837241  37.492185  8.982301
1       6.153745  17.357399  37.487367   74.735009  27.068139  6.337799
2       3.133578   9.986080  25.283831   63.912390  16.606843  3.538381
3       5.727347  14.911197  24.822934   73.201331  12.070142  1.442265
4       5.322287  13.824170  24.565734   75.146310   9.019561  9.344950
...          ...        ...        ...         ...        ...       ...
49675   0.556361   1.392335   9.378395   51.150241   0.504457  6.770894
49676   1.519181   4.070030  12.212918   59.177746   9.523318  5.738164
49677   2.586085   9.025256  26.634268   88.011060  29.867768  5.769692
49678   3.072033  13.966713  37.529058  111.127179  59.835298  2.525186
49679   7.046048  22.922780  54.985609  112.727780  61.685915  1.442386

        T7_theta   T7_alpha     T7_beta    T7_gamma  ...  Fp1_sampEm  \
0      21.704771  19.668520  161.314871   48.658398  ...    0.537817
1      16.841700  14.331228  208.847174   77.022406  ...    0.500941
2      22.099273  44.549127  252.074328  130.662022  ...    0.603994
3       6.447808  26.851468  212.230582   41.771628  ...    0.593225
4      37.736289  83.608551  199.070477  163.871981  ...    0.562527
...          ...        ...         ...         ...  ...         ...
49675  16.566279  26.783991   87.193127   12.336457  ...    0.453225
49676  14.871268  28.053340   99.563744   33.990589  ...    0.444251
49677  13.597221  21.359502   62.820428   10.298880  ...    0.638854
49678   6.756771  17.268029   48.452879   16.521767  ...    0.540240
49679   4.558886  13.147075   44.710342   16.821564  ...    0.575364

       T7_sampEm  T8_sampEm   Fp1_hfd    T7_hfd    T8_hfd   Fp1_dfa    T7_dfa  \
0       0.880359   0.607625  0.168947  0.175126  0.118092  0.364112  0.479208
1       0.568505   0.699973  0.110975  0.140263  0.193008  0.364112  0.479208
2       0.707746   1.187166  0.126657  0.190069  0.186417  0.364112  0.479208
3       0.630627   1.287854  0.150098  0.079742  0.119070  0.364112  0.479208
4       0.458308   0.804373  0.108262  0.170756  0.065233  0.364112  0.479208
...          ...        ...       ...       ...       ...       ...       ...
49675   0.575364   0.261993  0.149209  0.148587  0.196307  0.343993  0.364775
49676   0.602860   0.508843  0.123651  0.139572  0.112168  0.343993  0.364775
49677   0.519259   0.592504  0.179615  0.159102  0.182948  0.343993  0.364775
49678   0.517042   0.986495  0.120882  0.155216  0.111722  0.343993  0.364775
49679   0.484558   0.625706  0.120503  0.181527  0.140867  0.343993  0.364775

         T8_dfa  label
0      0.507154      1
1      0.507154      1
2      0.507154      1
3      0.507154      1
4      0.507154      1
...         ...    ...
49675  0.440935      1
49676  0.440935      1
49677  0.440935      1
49678  0.440935      1
49679  0.440935      1

[49680 rows x 25 columns]

In [2]:
merged_dfMDD

,Fp1_delta,Fp1_theta,Fp1_alpha,Fp1_beta,Fp1_gamma,T7_delta,T7_theta,T7_alpha,T7_beta,T7_gamma,...,Fp1_sampEm,T7_sampEm,T8_sampEm,Fp1_hfd,T7_hfd,T8_hfd,Fp1_dfa,T7_dfa,T8_dfa,label
0,6.603542,19.314987,48.768007,41.837241,37.492185,8.982301,21.704771,19.668520,161.314871,48.658398,...,0.537817,0.880359,0.607625,0.168947,0.175126,0.118092,0.364112,0.479208,0.507154,1
1,6.153745,17.357399,37.487367,74.735009,27.068139,6.337799,16.841700,14.331228,208.847174,77.022406,...,0.500941,0.568505,0.699973,0.110975,0.140263,0.193008,0.364112,0.479208,0.507154,1
2,3.133578,9.986080,25.283831,63.912390,16.606843,3.538381,22.099273,44.549127,252.074328,130.662022,...,0.603994,0.707746,1.187166,0.126657,0.190069,0.186417,0.364112,0.479208,0.507154,1
3,5.727347,14.911197,24.822934,73.201331,12.070142,1.442265,6.447808,26.851468,212.230582,41.771628,...,0.593225,0.630627,1.287854,0.150098,0.079742,0.119070,0.364112,0.479208,0.507154,1
4,5.322287,13.824170,24.565734,75.146310,9.019561,9.344950,37.736289,83.608551,199.070477,163.871981,...,0.562527,0.458308,0.804373,0.108262,0.170756,0.065233,0.364112,0.479208,0.507154,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49675,0.556361,1.392335,9.378395,51.150241,0.504457,6.770894,16.566279,26.783991,87.193127,12.336457,...,0.453225,0.575364,0.261993,0.149209,0.148587,0.196307,0.343993,0.364775,0.440935,1
49676,1.519181,4.070030,12.212918,59.177746,9.523318,5.738164,14.871268,28.053340,99.563744,33.990589,...,0.444251,0.602860,0.508843,0.123651,0.139572,0.112168,0.343993,0.364775,0.440935,1
49677,2.586085,9.025256,26.634268,88.011060,29.867768,5.769692,13.597221,21.359502,62.820428,10.298880,...,0.638854,0.519259,0.592504,0.179615,0.159102,0.182948,0.343993,0.364775,0.440935,1
49678,3.072033,13.966713,37.529058,111.127179,59.835298,2.525186,6.756771,17.268029,48.452879,16.521767,...,0.540240,0.517042,0.986495,0.120882,0.155216,0.111722,0.343993,0.364775,0.440935,1
49679,7.046048,22.922780,54.985609,112.727780,61.685915,1.442386,4.558886,13.147075,44.710342,16.821564,...,0.575364,0.484558,0.625706,0.120503,0.181527,0.140867,0.343993,0.364775,0.440935,1

In [3]:
import pandas as pd

# create an empty list to store the dataframes
df_list1 = []
merged_dfNONMDD = pd.DataFrame()
# loop through each CSV file and append its contents to df_list
for i in range(1,16):
    df = pd.read_csv(f'/content/drive/MyDrive/EC EEGTemporalPreprocessed/DatasetNonMDD/DatasetNonMDD{i}.csv')
    df_list1.append(df)

# concatenate the dataframes vertically into a single dataframe
# for data in df_list:
#     merged_df = pd.concat(data, axis=0, ignore_index=True)
#     merged_df = pd.concat([df1, d, ignore_index=True)
#     print(merged_df)

merged_dfNONMDD = pd.concat(df_list1, axis=0, ignore_index=True)

# print the merged dataframe
print(merged_dfNONMDD)

       Fp1_delta  Fp1_theta   Fp1_alpha    Fp1_beta   Fp1_gamma   T7_delta  \
0      30.063062  72.818351   73.639060  261.707503   53.050084  23.668406
1      10.833870  33.519527   91.350808  320.355795   57.869574  36.028169
2      16.091335  46.824724  117.739364  302.419317   75.903161  37.625761
3      18.921136  56.583418  145.888609  356.637722  131.353237  32.035617
4      20.072386  52.950613  134.161830  357.890043   34.350992  20.251198
...          ...        ...         ...         ...         ...        ...
26860   1.481759  13.984185   37.100740  292.872357   56.188630   2.830259
26861   7.029941  19.671274   25.961929  314.564945   79.870853   3.138491
26862  12.416143  34.480080   47.109487  268.116666  114.296125  18.367148
26863  11.978208  31.106084   44.568305  152.281272   77.370448  12.618178
26864   5.259768  12.651167   21.571008  126.006751   31.634021   4.467157

         T7_theta    T7_alpha     T7_beta    T7_gamma  ...  Fp1_sampEm  \
0       67.687877  120.688162  328.403203  131.662092  ...    0.916291
1      103.591803  202.143188  542.855437  220.587335  ...    0.325422
2      105.300366  211.356076  407.077141  157.973674  ...    0.641854
3       87.788503  161.158300  220.897919  134.514230  ...    1.178655
4       55.684724  112.474840   90.891246   28.796706  ...    0.916291
...           ...         ...         ...         ...  ...         ...
26860    7.293235    9.606063  187.718534    5.844000  ...    0.632523
26861   10.196369   15.537094  222.935931   56.726856  ...    0.251314
26862   45.089706   48.144819  173.141513   68.383210  ...    0.949081
26863   29.585650   34.381169  136.836645   17.366618  ...    0.674798
26864   12.193180   27.429664  145.571949   34.127820  ...    0.686716

       T7_sampEm   T8_sampEm   Fp1_hfd    T7_hfd    T8_hfd   Fp1_dfa  \
0       1.704748    1.446919  0.191968  0.154490  0.186480  0.705368
1       1.791759  228.158448  0.128392  0.107645  0.101059  0.705368
2       0.693147    1.098612  0.127511  0.070488  0.172175  0.705368
3       0.606136    1.098612  0.174224  0.135856  0.124544  0.705368
4       0.570545    0.459532  0.075731  0.111668  0.129196  0.705368
...          ...         ...       ...       ...       ...       ...
26860   0.693147    1.036092  0.140679  0.149012  0.126471  0.683038
26861   0.645138    0.869038  0.129457  0.127571  0.110279  0.683038
26862   0.908259    0.627550  0.137545  0.175932  0.136482  0.683038
26863   0.731613    0.493572  0.192584  0.150650  0.151928  0.683038
26864   0.545017    0.550046  0.126291  0.153602  0.161617  0.683038

         T7_dfa    T8_dfa  label
0      0.706739  0.791896      0
1      0.706739  0.791896      0
2      0.706739  0.791896      0
3      0.706739  0.791896      0
4      0.706739  0.791896      0
...         ...       ...    ...
26860  0.583566  0.579749      0
26861  0.583566  0.579749      0
26862  0.583566  0.579749      0
26863  0.583566  0.579749      0
26864  0.583566  0.579749      0

[26865 rows x 25 columns]

In [4]:
merged_dfNONMDD

,Fp1_delta,Fp1_theta,Fp1_alpha,Fp1_beta,Fp1_gamma,T7_delta,T7_theta,T7_alpha,T7_beta,T7_gamma,...,Fp1_sampEm,T7_sampEm,T8_sampEm,Fp1_hfd,T7_hfd,T8_hfd,Fp1_dfa,T7_dfa,T8_dfa,label
0,30.063062,72.818351,73.639060,261.707503,53.050084,23.668406,67.687877,120.688162,328.403203,131.662092,...,0.916291,1.704748,1.446919,0.191968,0.154490,0.186480,0.705368,0.706739,0.791896,0
1,10.833870,33.519527,91.350808,320.355795,57.869574,36.028169,103.591803,202.143188,542.855437,220.587335,...,0.325422,1.791759,228.158448,0.128392,0.107645,0.101059,0.705368,0.706739,0.791896,0
2,16.091335,46.824724,117.739364,302.419317,75.903161,37.625761,105.300366,211.356076,407.077141,157.973674,...,0.641854,0.693147,1.098612,0.127511,0.070488,0.172175,0.705368,0.706739,0.791896,0
3,18.921136,56.583418,145.888609,356.637722,131.353237,32.035617,87.788503,161.158300,220.897919,134.514230,...,1.178655,0.606136,1.098612,0.174224,0.135856,0.124544,0.705368,0.706739,0.791896,0
4,20.072386,52.950613,134.161830,357.890043,34.350992,20.251198,55.684724,112.474840,90.891246,28.796706,...,0.916291,0.570545,0.459532,0.075731,0.111668,0.129196,0.705368,0.706739,0.791896,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26860,1.481759,13.984185,37.100740,292.872357,56.188630,2.830259,7.293235,9.606063,187.718534,5.844000,...,0.632523,0.693147,1.036092,0.140679,0.149012,0.126471,0.683038,0.583566,0.579749,0
26861,7.029941,19.671274,25.961929,314.564945,79.870853,3.138491,10.196369,15.537094,222.935931,56.726856,...,0.251314,0.645138,0.869038,0.129457,0.127571,0.110279,0.683038,0.583566,0.579749,0
26862,12.416143,34.480080,47.109487,268.116666,114.296125,18.367148,45.089706,48.144819,173.141513,68.383210,...,0.949081,0.908259,0.627550,0.137545,0.175932,0.136482,0.683038,0.583566,0.579749,0
26863,11.978208,31.106084,44.568305,152.281272,77.370448,12.618178,29.585650,34.381169,136.836645,17.366618,...,0.674798,0.731613,0.493572,0.192584,0.150650,0.151928,0.683038,0.583566,0.579749,0
26864,5.259768,12.651167,21.571008,126.006751,31.634021,4.467157,12.193180,27.429664,145.571949,34.127820,...,0.686716,0.545017,0.550046,0.126291,0.153602,0.161617,0.683038,0.583566,0.579749,0

In [5]:
final_data = pd.concat([merged_dfNONMDD, merged_dfMDD], axis=0, ignore_index=True)
final_data

,Fp1_delta,Fp1_theta,Fp1_alpha,Fp1_beta,Fp1_gamma,T7_delta,T7_theta,T7_alpha,T7_beta,T7_gamma,...,Fp1_sampEm,T7_sampEm,T8_sampEm,Fp1_hfd,T7_hfd,T8_hfd,Fp1_dfa,T7_dfa,T8_dfa,label
0,30.063062,72.818351,73.639060,261.707503,53.050084,23.668406,67.687877,120.688162,328.403203,131.662092,...,0.916291,1.704748,1.446919,0.191968,0.154490,0.186480,0.705368,0.706739,0.791896,0
1,10.833870,33.519527,91.350808,320.355795,57.869574,36.028169,103.591803,202.143188,542.855437,220.587335,...,0.325422,1.791759,228.158448,0.128392,0.107645,0.101059,0.705368,0.706739,0.791896,0
2,16.091335,46.824724,117.739364,302.419317,75.903161,37.625761,105.300366,211.356076,407.077141,157.973674,...,0.641854,0.693147,1.098612,0.127511,0.070488,0.172175,0.705368,0.706739,0.791896,0
3,18.921136,56.583418,145.888609,356.637722,131.353237,32.035617,87.788503,161.158300,220.897919,134.514230,...,1.178655,0.606136,1.098612,0.174224,0.135856,0.124544,0.705368,0.706739,0.791896,0
4,20.072386,52.950613,134.161830,357.890043,34.350992,20.251198,55.684724,112.474840,90.891246,28.796706,...,0.916291,0.570545,0.459532,0.075731,0.111668,0.129196,0.705368,0.706739,0.791896,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76540,0.556361,1.392335,9.378395,51.150241,0.504457,6.770894,16.566279,26.783991,87.193127,12.336457,...,0.453225,0.575364,0.261993,0.149209,0.148587,0.196307,0.343993,0.364775,0.440935,1
76541,1.519181,4.070030,12.212918,59.177746,9.523318,5.738164,14.871268,28.053340,99.563744,33.990589,...,0.444251,0.602860,0.508843,0.123651,0.139572,0.112168,0.343993,0.364775,0.440935,1
76542,2.586085,9.025256,26.634268,88.011060,29.867768,5.769692,13.597221,21.359502,62.820428,10.298880,...,0.638854,0.519259,0.592504,0.179615,0.159102,0.182948,0.343993,0.364775,0.440935,1
76543,3.072033,13.966713,37.529058,111.127179,59.835298,2.525186,6.756771,17.268029,48.452879,16.521767,...,0.540240,0.517042,0.986495,0.120882,0.155216,0.111722,0.343993,0.364775,0.440935,1
76544,7.046048,22.922780,54.985609,112.727780,61.685915,1.442386,4.558886,13.147075,44.710342,16.821564,...,0.575364,0.484558,0.625706,0.120503,0.181527,0.140867,0.343993,0.364775,0.440935,1

In [6]:
from sklearn.preprocessing import normalize
# Normalize the dataframe
df_normalized = pd.DataFrame(normalize(final_data), columns=df.columns)

# View the normalized dataframe
print(df_normalized)

       Fp1_delta  Fp1_theta  Fp1_alpha  Fp1_beta  Fp1_gamma  T7_delta  \
0       0.046745   0.113225   0.114502  0.406930   0.082488  0.036802
1       0.012923   0.039984   0.108970  0.382143   0.069031  0.042977
2       0.021789   0.063405   0.159429  0.409502   0.102780  0.050949
3       0.023852   0.071330   0.183911  0.449586   0.165587  0.040385
4       0.025318   0.066788   0.169221  0.451414   0.043328  0.025543
...          ...        ...        ...       ...        ...       ...
76540   0.003040   0.007608   0.051245  0.279495   0.002756  0.036998
76541   0.008684   0.023264   0.069808  0.338257   0.054435  0.032799
76542   0.016824   0.058716   0.173276  0.572580   0.194313  0.037536
76543   0.013165   0.059854   0.160831  0.476235   0.256424  0.010822
76544   0.030360   0.098771   0.236925  0.485727   0.265795  0.006215

       T7_theta  T7_alpha   T7_beta  T7_gamma  ...  Fp1_sampEm  T7_sampEm  \
0      0.105248  0.187658  0.510635  0.204722  ...    0.001425   0.002651
1      0.123572  0.241131  0.647556  0.263132  ...    0.000388   0.002137
2      0.142586  0.286195  0.551218  0.213910  ...    0.000869   0.000939
3      0.110668  0.203160  0.278469  0.169572  ...    0.001486   0.000764
4      0.070236  0.141867  0.114643  0.036322  ...    0.001156   0.000720
...         ...       ...       ...       ...  ...         ...        ...
76540  0.090522  0.146353  0.476441  0.067409  ...    0.002477   0.003144
76541  0.085003  0.160351  0.569101  0.194288  ...    0.002539   0.003446
76542  0.088460  0.138960  0.408695  0.067002  ...    0.004156   0.003378
76543  0.028956  0.074002  0.207644  0.070804  ...    0.002315   0.002216
76544  0.019644  0.056649  0.192650  0.072482  ...    0.002479   0.002088

       T8_sampEm   Fp1_hfd    T7_hfd    T8_hfd   Fp1_dfa    T7_dfa    T8_dfa  \
0       0.002250  0.000298  0.000240  0.000290  0.001097  0.001099  0.001231
1       0.272164  0.000153  0.000128  0.000121  0.000841  0.000843  0.000945
2       0.001488  0.000173  0.000095  0.000233  0.000955  0.000957  0.001072
3       0.001385  0.000220  0.000171  0.000157  0.000889  0.000891  0.000998
4       0.000580  0.000096  0.000141  0.000163  0.000890  0.000891  0.000999
...          ...       ...       ...       ...       ...       ...       ...
76540   0.001432  0.000815  0.000812  0.001073  0.001880  0.001993  0.002409
76541   0.002909  0.000707  0.000798  0.000641  0.001966  0.002085  0.002520
76542   0.003855  0.001169  0.001035  0.001190  0.002238  0.002373  0.002869
76543   0.004228  0.000518  0.000665  0.000479  0.001474  0.001563  0.001890
76544   0.002696  0.000519  0.000782  0.000607  0.001482  0.001572  0.001900

          label
0      0.000000
1      0.000000
2      0.000000
3      0.000000
4      0.000000
...         ...
76540  0.005464
76541  0.005716
76542  0.006506
76543  0.004285
76544  0.004309

[76545 rows x 25 columns]

In [7]:
df_normalized

,Fp1_delta,Fp1_theta,Fp1_alpha,Fp1_beta,Fp1_gamma,T7_delta,T7_theta,T7_alpha,T7_beta,T7_gamma,...,Fp1_sampEm,T7_sampEm,T8_sampEm,Fp1_hfd,T7_hfd,T8_hfd,Fp1_dfa,T7_dfa,T8_dfa,label
0,0.046745,0.113225,0.114502,0.406930,0.082488,0.036802,0.105248,0.187658,0.510635,0.204722,...,0.001425,0.002651,0.002250,0.000298,0.000240,0.000290,0.001097,0.001099,0.001231,0.000000
1,0.012923,0.039984,0.108970,0.382143,0.069031,0.042977,0.123572,0.241131,0.647556,0.263132,...,0.000388,0.002137,0.272164,0.000153,0.000128,0.000121,0.000841,0.000843,0.000945,0.000000
2,0.021789,0.063405,0.159429,0.409502,0.102780,0.050949,0.142586,0.286195,0.551218,0.213910,...,0.000869,0.000939,0.001488,0.000173,0.000095,0.000233,0.000955,0.000957,0.001072,0.000000
3,0.023852,0.071330,0.183911,0.449586,0.165587,0.040385,0.110668,0.203160,0.278469,0.169572,...,0.001486,0.000764,0.001385,0.000220,0.000171,0.000157,0.000889,0.000891,0.000998,0.000000
4,0.025318,0.066788,0.169221,0.451414,0.043328,0.025543,0.070236,0.141867,0.114643,0.036322,...,0.001156,0.000720,0.000580,0.000096,0.000141,0.000163,0.000890,0.000891,0.000999,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76540,0.003040,0.007608,0.051245,0.279495,0.002756,0.036998,0.090522,0.146353,0.476441,0.067409,...,0.002477,0.003144,0.001432,0.000815,0.000812,0.001073,0.001880,0.001993,0.002409,0.005464
76541,0.008684,0.023264,0.069808,0.338257,0.054435,0.032799,0.085003,0.160351,0.569101,0.194288,...,0.002539,0.003446,0.002909,0.000707,0.000798,0.000641,0.001966,0.002085,0.002520,0.005716
76542,0.016824,0.058716,0.173276,0.572580,0.194313,0.037536,0.088460,0.138960,0.408695,0.067002,...,0.004156,0.003378,0.003855,0.001169,0.001035,0.001190,0.002238,0.002373,0.002869,0.006506
76543,0.013165,0.059854,0.160831,0.476235,0.256424,0.010822,0.028956,0.074002,0.207644,0.070804,...,0.002315,0.002216,0.004228,0.000518,0.000665,0.000479,0.001474,0.001563,0.001890,0.004285
76544,0.030360,0.098771,0.236925,0.485727,0.265795,0.006215,0.019644,0.056649,0.192650,0.072482,...,0.002479,0.002088,0.002696,0.000519,0.000782,0.000607,0.001482,0.001572,0.001900,0.004309

In [9]:
final_data.to_csv('final_epoched_data.csv')